spring:
  application:
    name: ecommerce-orders
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce-orders
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8083

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  instance:
    hostname: localhost